User roles added to user_model and users defaulted to standard in use…
pauga-family/reunion-back-end pull request #11
Opened 2024-05-06 15:10 UTC by d-diplodocus

User roles added to user_model.py and users defaulted to standard in user_service.py, changes should be implemented in database too

2024-05-07 01:19 UTC, paugajt commented
Everything looks good, just one minor comment. In `def _create_user_json(user, token)` we'll want to return the users role in JSON. We just need to update the existing code to look like this:
```
def _create_user_json(user, token):
    return jsonify(
        {
            "access_token": token,
            "id": user.id, 
            "firstName": user.firstName,
            "lastName": user.lastName,
            "email": user.email,
           "role": user.role
        }
    )
```

2024-05-07 02:53 UTC, paugajt requested changes
Everything looks good, just one minor comment. In `def _create_user_json(user, token)` we'll want to return the users role in JSON. We just need to update the existing code to look like this:
```
def _create_user_json(user, token):
    return jsonify(
        {
            "access_token": token,
            "id": user.id, 
            "firstName": user.firstName,
            "lastName": user.lastName,
            "email": user.email,
           "role": user.role
        }
    )
```

2024-05-07 17:33 UTC, d-diplodocus commented
Updated auth_routes.py to reflect comment - user roles added to def _create_user_json

2024-05-09 15:13 UTC, paugajt approved these changes

2024-05-09 23:35 UTC, merged